In [2]:
import numpy as np
import pandas as pd
from random import seed
import random

In [8]:
#시드고정
np.random.seed(1234)

#################################################################
#--------------------------천개
#랜덤추출2차원
a1=[]
for j in range(1000):
    for k in range(2) :
        ranarr2 = np.random.randint(0,2000)
        a1.append(ranarr2)
        
mid1 = np.array(a1)
final1 = np.reshape(mid1,(1000,2))

#간격추출2차원
a2=[]
for i in range(1000) :
    for j in range(2) :
        inarr2 = random.randrange(0,2000,2)
        a2.append(inarr2)
mid2 = np.array(a2)
final2 = np.reshape(mid2,(1000,2))
print(final2.shape)


#2차원 저장
df2 = pd.DataFrame(final1)
df2.to_csv('2DiRanData.csv',index=False)

du2 = pd.DataFrame(final2)
du2.to_csv('2DiUniData.csv',index=False)

#################################################################
#################################################################

#랜덤추출4차원
a3=[]
for j in range(1000):
    for k in range(4) :
        ranarr3 = np.random.randint(0,4000)
        a3.append(ranarr3)
        
mid3 = np.array(a3)
final3 = np.reshape(mid3,(1000,4))


#간격추출4차원
a4=[]
for i in range(1000) :
    for j in range(4) :
        inarr4 = random.randrange(0,8000,2)
        a4.append(inarr4)
mid4 = np.array(a4)
final4 = np.reshape(mid4,(1000,4))
print(final4.shape)


#4차원 저장
df4 = pd.DataFrame(final3)
df4.to_csv('4DiRanData.csv',index=False)

du4 = pd.DataFrame(final4)
du4.to_csv('4DiUniData.csv',index=False)

#################################################################
#################################################################

#랜덤추출8차원
a5=[]
for j in range(1000):
    for k in range(8) :
        ranarr5 = np.random.randint(0,8000)
        a5.append(ranarr5)
        
mid5 = np.array(a5)
final5 = np.reshape(mid5,(1000,8))


#간격추출8차원
a8=[]
for i in range(1000) :
    for j in range(8) :
        inarr8 = random.randrange(0,16000,2)
        a8.append(inarr8)
mid8 = np.array(a8)
final8 = np.reshape(mid8,(1000,8))
print(final8.shape)
 

#8차원 저장
df8 = pd.DataFrame(final5)
df8.to_csv('8DiRanData.csv',index=False)

du8 = pd.DataFrame(final8)
du8.to_csv('8DiUniData.csv',index=False)

#################################################################
#################################################################

#랜덤추출10차원
a7=[]
for j in range(1000):
    for k in range(10) :
        ranarr7 = np.random.randint(0,10000)
        a7.append(ranarr7)
        
mid7 = np.array(a7)
final7 = np.reshape(mid7,(1000,10))


#간격추출10차원
a10=[]
for i in range(1000) :
    for j in range(10) :
        inarr10 = random.randrange(0,20000,2)
        a10.append(inarr10)
mid10 = np.array(a10)
final10 = np.reshape(mid10,(1000,10))
print(final10.shape)

#10차원 저장
df10 = pd.DataFrame(final7)
df10.to_csv('10DiRanData.csv',index=False)

du10 = pd.DataFrame(final10)
du10.to_csv('10DiUniData.csv',index=False)

#################################################################

#------------------------------------------------만개

#################################################################

#랜덤추출2차원
a1=[]
for j in range(10000):
    for k in range(2) :
        ranarr2 = np.random.randint(0,20000)
        a1.append(ranarr2)
        
mid1 = np.array(a1)
final1 = np.reshape(mid1,(10000,2))

#간격추출2차원
a2=[]
for i in range(10000) :
    for j in range(2) :
        inarr2 = random.randrange(0,20000,2)
        a2.append(inarr2)
mid2 = np.array(a2)
final2 = np.reshape(mid2,(10000,2))
print(final2.shape)


#2차원 저장
df2 = pd.DataFrame(final1)
df2.to_csv('2DiRanData_10000.csv',index=False)

du2 = pd.DataFrame(final2)
du2.to_csv('2DiUniData_10000.csv',index=False)

#################################################################
#################################################################

#랜덤추출4차원
a3=[]
for j in range(10000):
    for k in range(4) :
        ranarr3 = np.random.randint(0,40000)
        a3.append(ranarr3)
        
mid3 = np.array(a3)
final3 = np.reshape(mid3,(10000,4))


#간격추출4차원
a4=[]
for i in range(10000) :
    for j in range(4) :
        inarr4 = random.randrange(0,80000,2)
        a4.append(inarr4)
mid4 = np.array(a4)
final4 = np.reshape(mid4,(10000,4))
print(final4.shape)


#4차원 저장
df4 = pd.DataFrame(final3)
df4.to_csv('4DiRanData_10000.csv',index=False)

du4 = pd.DataFrame(final4)
du4.to_csv('4DiUniData_10000.csv',index=False)

#################################################################
#################################################################

#랜덤추출8차원
a5=[]
for j in range(10000):
    for k in range(8) :
        ranarr5 = np.random.randint(0,80000)
        a5.append(ranarr5)
        
mid5 = np.array(a5)
final5 = np.reshape(mid5,(10000,8))

#간격추출8차원
a8=[]
for i in range(10000) :
    for j in range(8) :
        inarr8 = random.randrange(0,160000,2)
        a8.append(inarr8)
mid8 = np.array(a8)
final8 = np.reshape(mid8,(10000,8))
print(final8.shape)


#8차원 저장
df8 = pd.DataFrame(final5)
df8.to_csv('8DiRanData_10000.csv',index=False)

du8 = pd.DataFrame(final8)
du8.to_csv('8DiUniData_10000.csv',index=False)

#################################################################
#################################################################

#랜덤추출10차원
a7=[]
for j in range(10000):
    for k in range(10) :
        ranarr7 = np.random.randint(0,100000)
        a7.append(ranarr7)
        
mid7 = np.array(a7)
final7 = np.reshape(mid7,(10000,10))


#간격추출10차원
a10=[]
for i in range(10000) :
    for j in range(10) :
        inarr10 = random.randrange(0,200000,2)
        a10.append(inarr10)
mid10 = np.array(a10)
final10 = np.reshape(mid10,(10000,10))
print(final10.shape)


#10차원 저장
df10 = pd.DataFrame(final7)
df10.to_csv('10DiRanData_10000.csv',index=False)

du10 = pd.DataFrame(final10)
du10.to_csv('10DiUniData_10000.csv',index=False)

##################################################################

#------------------------------------------------십만개

#################################################################
#랜덤추출2차원
a1=[]
for j in range(100000):
    for k in range(2) :
        ranarr2 = np.random.randint(0,200000)
        a1.append(ranarr2)
        
mid1 = np.array(a1)
final1 = np.reshape(mid1,(100000,2))

#간격추출2차원
a2=[]
for i in range(100000) :
    for j in range(2) :
        inarr2 = random.randrange(0,200000,2)
        a2.append(inarr2)
mid2 = np.array(a2)
final2 = np.reshape(mid2,(100000,2))
print(final2.shape)


#2차원 저장
df2 = pd.DataFrame(final1)
df2.to_csv('2DiRanData_100000.csv',index=False)

du2 = pd.DataFrame(final2)
du2.to_csv('2DiUniData_100000.csv',index=False)

#################################################################
#################################################################

#랜덤추출4차원
a3=[]
for j in range(100000):
    for k in range(4) :
        ranarr3 = np.random.randint(0,400000)
        a3.append(ranarr3)
        
mid3 = np.array(a3)
final3 = np.reshape(mid3,(100000,4))


#간격추출4차원
a4=[]
for i in range(100000) :
    for j in range(4) :
        inarr4 = random.randrange(0,800000,2)
        a4.append(inarr4)
mid4 = np.array(a4)
final4 = np.reshape(mid4,(100000,4))
print(final4.shape)


#4차원 저장
df4 = pd.DataFrame(final3)
df4.to_csv('4DiRanData_100000.csv',index=False)

du4 = pd.DataFrame(final4)
du4.to_csv('4DiUniData_100000.csv',index=False)

#################################################################
#################################################################

#랜덤추출8차원
a5=[]
for j in range(100000):
    for k in range(8) :
        ranarr5 = np.random.randint(0,800000)
        a5.append(ranarr5)
        
mid5 = np.array(a5)
final5 = np.reshape(mid5,(100000,8))

#간격추출8차원
a8=[]
for i in range(100000) :
    for j in range(8) :
        inarr8 = random.randrange(0,1600000,2)
        a8.append(inarr8)
mid8 = np.array(a8)
final8 = np.reshape(mid8,(100000,8))
print(final8.shape)


#8차원 저장
df8 = pd.DataFrame(final5)
df8.to_csv('8DiRanData_100000.csv',index=False)

du8 = pd.DataFrame(final8)
du8.to_csv('8DiUniData_100000.csv',index=False)

#################################################################
#################################################################

#랜덤추출10차원
a7=[]
for j in range(100000):
    for k in range(10) :
        ranarr7 = np.random.randint(0,1000000)
        a7.append(ranarr7)
        
mid7 = np.array(a7)
final7 = np.reshape(mid7,(100000,10))


#간격추출10차원
a10=[]
for i in range(100000) :
    for j in range(10) :
        inarr10 = random.randrange(0,2000000,2)
        a10.append(inarr10)
mid10 = np.array(a10)
final10 = np.reshape(mid10,(100000,10))
print(final10.shape)


#10차원 저장
df10 = pd.DataFrame(final7)
df10.to_csv('10DiRanData_100000.csv',index=False)

du10 = pd.DataFrame(final10)
du10.to_csv('10DiUniData_100000.csv',index=False)

#################################################################

#------------------------------------------------백만개

#################################################################
#랜덤추출2차원
a1=[]
for j in range(1000000):
    for k in range(2) :
        ranarr2 = np.random.randint(0,2000000)
        a1.append(ranarr2)
        
mid1 = np.array(a1)
final1 = np.reshape(mid1,(1000000,2))

#간격추출2차원
a2=[]
for i in range(1000000) :
    for j in range(2) :
        inarr2 = random.randrange(0,2000000,2)
        a2.append(inarr2)
mid2 = np.array(a2)
final2 = np.reshape(mid2,(1000000,2))
print(final2.shape)


#2차원 저장
df2 = pd.DataFrame(final1)
df2.to_csv('2DiRanData_1000000.csv',index=False)

du2 = pd.DataFrame(final2)
du2.to_csv('2DiUniData_1000000.csv',index=False)

#################################################################
#################################################################

#랜덤추출4차원
a3=[]
for j in range(1000000):
    for k in range(4) :
        ranarr3 = np.random.randint(0,4000000)
        a3.append(ranarr3)
        
mid3 = np.array(a3)
final3 = np.reshape(mid3,(1000000,4))


#간격추출4차원
a4=[]
for i in range(1000000) :
    for j in range(4) :
        inarr4 = random.randrange(0,8000000,2)
        a4.append(inarr4)
mid4 = np.array(a4)
final4 = np.reshape(mid4,(1000000,4))
print(final4.shape)


#4차원 저장
df4 = pd.DataFrame(final3)
df4.to_csv('4DiRanData_1000000.csv',index=False)

du4 = pd.DataFrame(final4)
du4.to_csv('4DiUniData_1000000.csv',index=False)

#################################################################
#################################################################

#랜덤추출8차원
a5=[]
for j in range(1000000):
    for k in range(8) :
        ranarr5 = np.random.randint(0,8000000)
        a5.append(ranarr5)
        
mid5 = np.array(a5)
final5 = np.reshape(mid5,(1000000,8))

#간격추출8차원
a8=[]
for i in range(1000000) :
    for j in range(8) :
        inarr8 = random.randrange(0,16000000,2)
        a8.append(inarr8)
mid8 = np.array(a8)
final8 = np.reshape(mid8,(1000000,8))
print(final8.shape)

#8차원 저장
df8 = pd.DataFrame(final5)
df8.to_csv('8DiRanData_1000000.csv',index=False)

du8 = pd.DataFrame(final8)
du8.to_csv('8DiUniData_1000000.csv',index=False)

#################################################################
#################################################################

#랜덤추출10차원
a7=[]
for j in range(1000000):
    for k in range(10) :
        ranarr7 = np.random.randint(0,10000000)
        a7.append(ranarr7)
        
mid7 = np.array(a7)
final7 = np.reshape(mid7,(1000000,10))


#간격추출10차원
a10=[]
for i in range(1000000) :
    for j in range(10) :
        inarr10 = random.randrange(0,20000000,2)
        a10.append(inarr10)
mid10 = np.array(a10)
final10 = np.reshape(mid10,(1000000,10))
print(final10.shape)

#10차원 저장
df10 = pd.DataFrame(final7)
df10.to_csv('10DiRanData_1000000.csv',index=False)

du10 = pd.DataFrame(final10)
du10.to_csv('10DiUniData_1000000.csv',index=False)


(1000, 2)
(1000, 4)
(1000, 8)
(1000, 10)
(10000, 2)
(10000, 4)
(10000, 8)
(10000, 10)
(100000, 2)
(100000, 4)
(100000, 8)
(100000, 10)
(1000000, 2)
(1000000, 4)
(1000000, 8)
(1000000, 10)


In [7]:
print(final5)

[[ 944867 6559073  474304 ... 6238276 1545071  305188]
 [6085312 3686259 7148085 ...  837034 5444265 5870891]
 [1834214 4476760 3007016 ... 3035823 1606758 5843498]
 ...
 [3699939 3477838 7499381 ... 4484710 2434147 6935300]
 [1602209 4859380 3277267 ... 1866955  179647 5919830]
 [1951335 2471454 1348457 ... 7829229 5661227 6347386]]
