In [843]:
import numpy as np
import pandas as pd
from random import seed
from random import random
import math

In [851]:
def getPermuCount(arr):
    row = len(arr)
    permu_num = []
    for j in range(row):
        col = len(arr[j])
        num = my_factorial(col)
        permu_num.append(num)
        num=0
    return permu_num

def getInvCount(arr):
    inv_count_row = []
    col = len(arr[0])
    row = len(arr)
    for k in range(row):
        inv_count = 0
        for i in range(col-1):
            for j in range(i+1,col):
                if (arr[k][i] > arr[k][j]):
                    inv_count += 1
        inv_count_row.append(inv_count)
    return inv_count_row

def MakeZeroInv(arr):
    for i in range(len(arr)-1):
        for j in range(i+1,len(arr)):
            if((arr[i])>(arr[j])):
                temp=arr[i]
                arr[i]=arr[j]
                arr[j]=temp
    return arr
        
        

def my_factorial(n): 
    if(n > 1): 
        return n * my_factorial(n - 1) 
    else: 
        return 1
    

In [898]:
def CreateRangePermuArr_Ver22 (dim, num):

    count= 0 
    maxInvNum = (int)(dim*(dim-1)/2)
    newa=[]
    permu=[]
    fi=[]
    loop = math.ceil(num/maxInvNum)
    
    for i in range(loop):
        seed(i)
        permu=[]
        for n in range(dim):
            sed = random()
            new = sed
            permu.append(new)
        permu = MakeZeroInv(permu)
        newa.extend(permu)

        count = count +1
        for j in range(dim):
            k=dim-j-1
            for m in range(k):
                if(count<num):
                    temp = permu[m]
                    permu[m] = permu[m+1]
                    permu[m+1]=temp
                    newa.extend(permu)

                    count = count+1
                if(count==num):
                    fi = np.array(newa).reshape(num,dim)
    
    result_df = pd.DataFrame(fi)   #데이터 프레임 형식으로 만들기
    df_shuffled = result_df.sample(frac=1).reset_index(drop=True)  #섞기
    return df_shuffled
            

In [906]:
dim=[5,10,15,20,30,40,50]
data=[1000,10000,30000]

for i in data:
    for j in dim:
        f = CreateRangePermuArr_Ver22(j,i)
        h = np.array(f)
        g = getInvCount(h)

        df2_1000 = f
        df2_1000.to_csv('Cre_{0}_{1}.csv'.format(j,i),index=False)

In [864]:
def CreateRangePermuArr_Ver21 (dim, num):

    count= 0 
    maxInvNum = (int)(dim*(dim-1)/2)
    newa=[]
    permu=[]
    fi=[]
    loop = math.ceil(num/maxInvNum)
    
    for i in range(loop):
        seed(i)
        sed=[]
        sed = np.random.rand(1,dim)
        for k in range(dim-1):
            for l in range(k+1,dim):
                if((sed[k])>(sed[l])):
                    temp=sed[k]
                    sed[k]=sed[l]
                    sed[l]=temp
        newa.extend(sed)

        count = count +1
        for j in range(dim):
            k=dim-j-1
            for m in range(k):
                if(count<num):
                    temp = newpermu[m]
                    newpermu[m] = newpermu[m+1]
                    newpermu[m+1]=temp
                    newa.extend(newpermu)

                    count = count+1
                if(count==num):
                    fi = np.array(newa).reshape(num,dim)
                    return fi
            

In [807]:
def CreateRangePermuArr_Ver20 (dim, num):

    count= 0 
    maxInvNum = (int)(dim*(dim-1)/2)
    newa=[]
    permu=[]
    fi=[]
    loop = math.ceil(num/maxInvNum)
    
    for i in range(loop):
        seed(i)
        sed = random()
        permu=[]
        for n in range(dim):
            new = sed +n
            permu.append(new)
        newa.extend(permu)

        count = count +1
        for j in range(dim):
            k=dim-j-1
            for m in range(k):
                if(count<num):
                    temp = permu[m]
                    permu[m] = permu[m+1]
                    permu[m+1]=temp
                    newa.extend(permu)

                    count = count+1
                if(count==num):
                    fi = np.array(newa).reshape(num,dim)
                    return fi
            

In [837]:
c= CreateRangePermuArr_Ver20(5,30000)
df5_1000 = pd.DataFrame(c)
df5_1000.to_csv('Cre_5_30000.csv',index=False)


In [806]:
def CreateRangePermuArr_Ver11 (dim, num):

    count= 0 
    maxInvNum = (int)(dim*(dim-1)/2)
    newa=[]
    loop = math.ceil(num/maxInvNum)
    
    for i in range(loop):
        permu = [1,2,3,4,5]
        newa.extend(permu)
        count = count +1
        for j in range(dim):
            k=dim-j-1
            for m in range(k):
                if(count<num):
                    temp = permu[m]
                    permu[m] = permu[m+1]
                    permu[m+1]=temp
                    newa.extend(permu)
                    count = count+1
                if(count==num):
                    fi = np.array(newa).reshape(num,dim)
                    return fi

In [525]:
def CreateRangePermuArr_Ver10 (dim, num):

    count= 0 
    maxInvNum = (int)(dim*(dim-1)/2)
    newa=[]
    permu = [1,2,3,4,5]
    for i in range(maxInvNum+1):
        """        
        np.random.seed(i)
        permu = np.random.rand(1,dim)
        """
        for j in range(dim):
            k=dim-j-1
            for m in range(k):
                temp = permu[m]
                permu[m] = permu[m+1]
                permu[m+1]=temp
                newa.extend(permu)
                count = count+1
                if(count==num):
                    fi = np.array(newa).reshape(num,dim)
                    return fi
        #newa.append([1,2,3,4,5])

        

In [483]:
def CreateRangePermuArr_Ver6 (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    ind = (int)(2*dim-4)
    indhalf = (int)(ind/2)
    loop = math.ceil(num/ind)
    init=[]
    newa=[]

    for n in range (1,dim+1):
        init.append(n)
        count=0

    for i in range(1,loop+1):
        for j in range(1,ind+1):
            
            if(j<=indhalf):
                newind = j
                temp = init[newind]
                init[newind] = init[newind+1]
                init[newind+1] = temp
                newa.extend(init)
                count =  count + 1
                
            else: 
                newind = (j*(indhalf-1))%indhalf
                temp = init[newind]
                init[newind] = init[newind+1]
                init[newind+1] = temp
                newa.extend(init)
                count = count + 1
                
            if(count>=num): 
                fi = np.array(newa).reshape(num,dim)
                return fi

In [459]:
c=CreateRangePermuArr_Ver6(6,100)
print(c)
print(c.shape)
d = getInvCount(c)
print(d)
#df2_1000 = pd.DataFrame(d)
#df2_1000.to_csv('histogram.csv',index=False)

15
[[1 3 2 4 5 6]
 [1 3 4 2 5 6]
 [1 3 4 5 2 6]
 [1 3 4 5 6 2]
 [1 3 4 6 5 2]
 [1 3 6 4 5 2]
 [1 6 3 4 5 2]
 [6 1 3 4 5 2]
 [6 3 1 4 5 2]
 [6 3 4 1 5 2]
 [6 3 4 5 1 2]
 [6 3 4 5 2 1]
 [6 3 4 2 5 1]
 [6 3 2 4 5 1]
 [6 2 3 4 5 1]
 [2 6 3 4 5 1]
 [2 3 6 4 5 1]
 [2 3 4 6 5 1]
 [2 3 4 5 6 1]
 [2 3 4 5 1 6]
 [2 3 4 1 5 6]
 [2 3 1 4 5 6]
 [2 1 3 4 5 6]
 [1 2 3 4 5 6]
 [1 3 2 4 5 6]
 [1 3 4 2 5 6]
 [1 3 4 5 2 6]
 [1 3 4 5 6 2]
 [1 3 4 6 5 2]
 [1 3 6 4 5 2]
 [1 6 3 4 5 2]
 [6 1 3 4 5 2]
 [6 3 1 4 5 2]
 [6 3 4 1 5 2]
 [6 3 4 5 1 2]
 [6 3 4 5 2 1]
 [6 3 4 2 5 1]
 [6 3 2 4 5 1]
 [6 2 3 4 5 1]
 [2 6 3 4 5 1]
 [2 3 6 4 5 1]
 [2 3 4 6 5 1]
 [2 3 4 5 6 1]
 [2 3 4 5 1 6]
 [2 3 4 1 5 6]
 [2 3 1 4 5 6]
 [2 1 3 4 5 6]
 [1 2 3 4 5 6]
 [1 3 2 4 5 6]
 [1 3 4 2 5 6]
 [1 3 4 5 2 6]
 [1 3 4 5 6 2]
 [1 3 4 6 5 2]
 [1 3 6 4 5 2]
 [1 6 3 4 5 2]
 [6 1 3 4 5 2]
 [6 3 1 4 5 2]
 [6 3 4 1 5 2]
 [6 3 4 5 1 2]
 [6 3 4 5 2 1]
 [6 3 4 2 5 1]
 [6 3 2 4 5 1]
 [6 2 3 4 5 1]
 [2 6 3 4 5 1]
 [2 3 6 4 5 1]
 [2 3 4 6 5 1]
 [2 3 4

In [446]:
def CreateRangePermuArr_Ver5 (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    init=[]
    newa=[]
    allarr = my_factorial(dim)

    for n in range (1,dim+1):
        init.append(n)
        count=0

    for i in range(1,num+1):   #4
        ind = (int)(2*dim-4)   #6
        indhalf = (int)(ind/2)   #3
        for l in range(2):
            for j in range (1,indhalf+1):  #1~3
                newin = j
                temp=init[j]
                init[j]=init[j+1]
                init[j+1]=temp
                
                newa.extend(init)
            for k in range (1,indhalf+1):  #4~6
                newin = indhalf-k
            
            
        newa.extend(init)
    fi.append(newa)
    return fi

In [ ]:
def CreateRangePermuArr_Ver4 (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    init=[]
    newa=[]
    allarr = my_factorial(dim)

    for n in range (1,dim+1):
        init.append(n)
        count=0

    for i in range(1,num+1):   #4
        ind = (int)(2*dim-4)   #6
        indhalf = (int)(ind/2)   #3
        if(i%ind==0):
            newin=0
        else if (i%indhalf==0):
            newin=indhalf
        else :
            if((i==indhalf+1)||(i==indhalf-1)):
                newin= indhalf-1
            if((i==indhalf+2)||(i==indhalf-2)):
                newin= indhalf-2
        newa.extend(init)
    fi.append(newa)
    return fi



            
    
    i%ind = 0  newin = 0
    i%ind = 1  newin = 1
    i%ind = 2  newin = 2
    i%ind = 3  newin = 1
    
    ind = indhalf +1,-1 newind-1
    ind = indhalf +2, -2 newind-2
    ind%indhalf == 0 newind =     
    ind
    
    i%ind = ind/2  newin = ind/2
    i%ind = ind/2-1, ind/2+1 newin = ind/2-1
    
            
"""            
            for m in range(dim-1):  #5
                temp = init[m]
                init[m]=init[m+1]
                init[m+1]=temp
                newa.extend(init)
                count = count+1
                print(count)
                if(count>num):
                    print(newa)
                    fi = np.array(newa).reshape(num,dim)
                    return fi
                
"""
    

In [402]:
def CreateRangePermuArr_Ver3 (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    init=[]
    newa=[]
    allarr = my_factorial(dim)

    for n in range (1,dim+1):
        init.append(n)
        count=0

    for i in range(1,num+1):
        ind = (int)(2*dim-4)
        for j in range((int)(ind/2),ind):
            if(i%ind==(ind-j)):
                newin=j
                print(ind)
                print(i)
                print(j)
                print(newin)
                temp = init[j]
                init[j]=init[j+1]
                init[j+1]=temp
        newa.extend(init)
    fi.append(newa)
    return fi



            
    
    i%ind = 0  newin = 0
    i%ind = 1  newin = 1
    i%ind = 2  newin = 2
    i%ind = 3  newin = 1
    
    ind = indhalf +1,-1 newind-1
    ind = indhalf +2, -2 newind-2
    ind%indhalf == 0 newind =     
    ind
    
    i%ind = ind/2  newin = ind/2
    i%ind = ind/2-1, ind/2+1 newin = ind/2-1
    
            
"""            
            for m in range(dim-1):  #5
                temp = init[m]
                init[m]=init[m+1]
                init[m+1]=temp
                newa.extend(init)
                count = count+1
                print(count)
                if(count>num):
                    print(newa)
                    fi = np.array(newa).reshape(num,dim)
                    return fi
                
"""
    

'            \n            for m in range(dim-1):  #5\n                temp = init[m]\n                init[m]=init[m+1]\n                init[m+1]=temp\n                newa.extend(init)\n                count = count+1\n                print(count)\n                if(count>num):\n                    print(newa)\n                    fi = np.array(newa).reshape(num,dim)\n                    return fi\n                \n'

In [387]:
def CreateRangePermuArr_Ver2 (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    init=[]
    newa=[]
    allarr = my_factorial(dim)

    for n in range (1,dim+1):
        init.append(n)
        count=0

    for i in range(1,dim+1):   #1~6
        loop =(int)((allarr/dim)/(dim-1))
        for j in range(loop):  #24
            for m in range(dim-1):  #5
                temp = init[m]
                init[m]=init[m+1]
                init[m+1]=temp
                newa.extend(init)
                count = count+1
                print(count)
                if(count>num):
                    print(newa)
                    fi = np.array(newa).reshape(num,dim)
                    return fi
                

    

In [348]:

def CreateRangePermuArr (dim, num):
    maxInvNum = (int)(dim*(dim-1)/2)
    init=[]
    newa=[]
    loop = math.ceil(num/(maxInvNum*dim)) 
    print(loop)
    for n in range (1,dim+1):
        init.append(n)
        count=1
        
    for m in range(loop):    
        if(num>=dim*maxInvNum):
            for i in range(dim):
                for j in range(maxInvNum):
                    k=j+(maxInvNum-1)-i
                    one= (int)(((maxInvNum/2)-1)-((k)%(maxInvNum/2)))
                    two= (int)(((maxInvNum/2)-1)-((k)%(maxInvNum/2))+1)
                    temp = init[one]
                    init[one]=init[two]
                    init[two] = temp
                    newa.extend(init)
                    count = count+1
                    if(count>num):
                        fi = np.array(newa).reshape(num,dim)
                        return fi
                
        else : return print("{0}이상의 데이터를 생성해 주세요.".format(dim*maxInvNum))
    

In [315]:
b=CreateRangePermuArr(3,25)
print(b)
getInvCount(b)
print(b.shape)

3
[[2 1 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [2 1 3]
 [1 2 3]
 [2 1 3]
 [2 1 3]
 [1 2 3]
 [2 1 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [2 1 3]
 [1 2 3]
 [2 1 3]
 [2 1 3]
 [1 2 3]
 [2 1 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [2 1 3]
 [1 2 3]
 [2 1 3]]
(25, 3)


In [283]:

new=[]

for i in range(4):
    init=[1,2,3,4]
    new.extend(init)
    for j in range(6):
        k=j+5-i
        one= 2-((k)%3)
        two= 2-((k)%3)+1
        temp = init[one]
        init[one]=init[two]
        init[two] = temp
        #print("one{0},two{1}".format(one,two))
        new.extend(init)

fi = np.array(new).reshape(28,4)


In [125]:
def getInvCount(arr):
    inv_count_row = []
    col = len(arr[0])
    row = len(arr)
    for k in range(row):
        inv_count = 0
        for i in range(col-1):
            for j in range(i+1,col):
                if (arr[k][i] > arr[k][j]):
                    inv_count += 1
        inv_count_row.append(inv_count)
    return inv_count_row

In [93]:
getInvCount(fi)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 0,
 1,
 2,
 3,
 4,
 5,
 4,
 0,
 1,
 2,
 3,
 4,
 5,
 6]